apiVersion: apps/v1
kind: Pod
metadata:
  name: generativeai
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: generativeai
  template:
    metadata:
      labels:
        app: generativeai
    spec:
      containers:
      - name: genai-container
        image: xerxez786/my-streamlit-app:latest 
        ports:
        - containerPort: 8501
