apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-streamlit-app
  labels:
    app: my-streamlit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: xerxez786/my-streamlit-app:latest
        ports:
        - containerPort: 8501
