name: Security Analysis

on:
    push:
      branches:
        - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit requests

    - name: Run Bandit
      run: bandit -r . -f json -o bandit-report.json

    - name: Upload Bandit results
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: bandit-report.json

    - name: Upload Bandit report to DefectDojo
      run: python upload_to_defectdojo.py
      env:
        DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
        DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
        DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
